### ISSUE TITLE
find better management for updating, installing and linking dotfiles

### ISSUE THREAD

**Issue by joclement** [joclement/Dotfiles#6]
good source to start research is here:

https://dotfiles.github.io/

look at this part:
General-purpose dotfile utilities

**Comment by flyingdutchman23** [comment]
One solution might be [dotbot](http://github.com/anishathalye/dotbot). 
- [ ] check it out

**Comment by flyingdutchman23** [comment]
Maybe it is simpler and more secure for the zsh Dotfiles management to avoid a plugin manager.

**Comment by flyingdutchman23** [comment]
- [ ] Integrate [dotbot](https://github.com/anishathalye/dotbot) into own Dotfiles
